### PR TITLE
LORA_E5: correct pin table

### LINKED ISSUE #19: LORA E5 - LPUART and other UART pins
https://github.com/ARMmbed/stm32customtargets/blob/e7db2bbc78af3db31695a252e8b9f243bc37d754/TARGET_STM32WL/TARGET_LORA_E5/PeripheralPins.c#L133-L159

I would like to use the LPUART on PC0+PC1. I've tried changing the definition to:
```
MBED_WEAK const PinMap PinMap_UART_TX[] = {
    {PA_2,       UART_2,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART2)}, // Connected to STDIO_UART_RX
    {PA_2_ALT0,  LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF8_LPUART1)}, // Connected to STDIO_UART_RX
//    {PA_9,       UART_1,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART1)},
//    {PB_6,       UART_1,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART1)},
//    {PB_11,      LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF8_LPUART1)}, // Connected to LED3
    {PC_1,       LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF8_LPUART1)},
//    {PA_2,       LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF8_LPUART1)}, // Connected to STDIO_UART_RX
    {PA_9,       UART_1,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART1)},
    {PB_6,       UART_1,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART1)},
    {NC, NC, 0}
};

MBED_WEAK const PinMap PinMap_UART_RX[] = {
    {PA_3,       UART_2,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART2)}, // Connected to STDIO_UART_RX
    {PA_3_ALT0,  LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF8_LPUART1)}, // Connected to STDIO_UART_RX
//    {PA_10,      UART_1,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART1)},
//    {PB_7,       UART_1,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART1)},
//    {PB_10,      LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF8_LPUART1)},
    {PC_0,       LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF8_LPUART1)},
//    {PA_3,       LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF8_LPUART1)}, // Connected to STDIO_UART_RX
    {PA_10,      UART_1,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART1)},
    {PB_7,       UART_1,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART1)},
    {NC, NC, 0}
};
```

This looks like it is working now, but it did not work the previous time. Maybe I had a mistake.

Can someone with more experience with the mbed custom target definitions please have a look and add the LPUART and  additional UART pins? @hallard

### PR DESCRIPTION
**Pull request by jeromecoutant**
Fix #19 

For information, used command to generate file templates:
```
python targets/TARGET_STM/tools/STM32_gen_PeripheralPins.py -m "STM32WLE5JCIx.xml"
```

### CODE REVIEW

**Comment by jeromecoutant** [comment]
@hallard @jpmeijers

**Comment by jeromecoutant** [comment]
I added changes for RAK3172. This is a smaller MCU, with less pins.
Please approve this PR if this is OK for you

**Comment by hallard** [comment]
Quick view looks better now, thanks.

**Comment by jpmeijers** [comment]
Looks good to me

**Comment by hallard** [comment]
BTW could you please add a mbed-os-6.14.0 tag?

**Comment by hallard** [comment]
Guys, I didn't pay attention to pins modified (just looked on ones added) and I just spent time looking from a dirty bug. My BufferedSerial worked fine and does not anymore after this commit. It's connected to PA_2 PA_3 (Named serial 2 on LoRa E5) and since it's now 

```cpp 
// PinMap_UART_TX
{PA_2,       UART_2,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART2)},
{PA_2_ALT0,  LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF8_LPUART1)},

// PinMap_UART_RX 
{PA_3,       UART_2,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART2)},
{PA_3_ALT0,  LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF8_LPUART1)},
```

And works with old scheme

```cpp
//PinMap_UART_TX
{PA_2, LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF8_LPUART1)}, 

//PinMap_UART_RX 
{PA_3, LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF8_LPUART1)},

```
Not sure of the cause but that change broke the code, any chance to revert back ? I always fixed a nasty bug related to modbus (same pins) few days ago and I'm pretty sure it's related to same things.

**Comment by hallard** [comment]
Ok, fixed changing my `serial` declaration

```cpp
// Instance Serial
//static BufferedSerial modbus_serial(PA_2, PA_3);
static BufferedSerial modbus_serial(PA_2_ALT0, PA_3_ALT0);
````

And here we go

**Comment by jeromecoutant** [comment]
OK,
I don't see any problem if you want to set back PA_2 with LPUART_1 and PA_2_ALT0 with UART_2

**Comment by hallard** [comment]
Yeah even if it works otherwise using ALT_0 may be letting default would avoid end user some headache 

You mean something like that? @jpmeijers makes sense to you?

```
// PinMap_UART_TX
{PA_2_ALT0,       UART_2,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART2)},
{PA_2,  LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF8_LPUART1)},

// PinMap_UART_RX 
{PA_3_ALT0,       UART_2,   STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF7_USART2)},
{PA_3, LPUART_1, STM_PIN_DATA(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF8_LPUART1)},
```

**Comment by jpmeijers** [comment]
I actually prefer the way it currently is.

```
UnbufferedSerial pc(PB_6, PB_7); // UART_1
// UnbufferedSerial loop(PA_2, PA_3); // UART_2
// UnbufferedSerial loop(PA_2_ALT0, PA_3_ALT0); // LPUART_1
// UnbufferedSerial loop(PC_1, PC_0); // LPUART_1
```

PA2/PA3 are the only two pins on which UART2 can be used, so it makes sense keeping them as the default.

LPUART is the only one that can be used on PC0/PC1 and should therefore be the default there.

Which leaves us with LPUART as the "Alternate" function on PA2/PA3 - like it is currently.

Edit:
Why do you specifically want to use LPUART on PA2/PA3, and not the default UART2? For me the expected behaviour should be UART2.

**Comment by hallard** [comment]
Sounds good to me keeping things like that.

> Why do you specifically want to use LPUART on PA2/PA3, and not the default UART2? For me the expected behaviour should be UART2.

Because I'm using 2 Serial devices on 2 different projects, each is connected to PA_2/PA_3 of LoRa E5. Really nothing fancy on serial port communication, just used `bufferedSerial` and API  from start without any issue
But since this change it has stopped to works, on both projects.  

So now, since these changes,  I changed 
```cpp
static BufferedSerial modbus_serial(PA_2, PA_3);
```
to 
```cpp
static BufferedSerial modbus_serial(PA_2_ALT0, PA_3_ALT0);
```
and things worked back again, don't ask me why just using UART2 it does not work, I have no idea, code after serial init in project 2 is simple as that (looking from frame sent on regular basis by serial device)

```cpp
    while (_sensor_serial.readable())
    {
        uint8_t c;
        _sensor_serial.read(&c, 1);
        // blah blah
    }
```

**Comment by jeromecoutant** [comment]
> don't ask me why just using UART2 it does not work

Maybe because UART2 is missing in
https://github.com/ARMmbed/mbed-os/blob/master/targets/TARGET_STM/TARGET_STM32WL/serial_device.c#L61-L73

:-(

**Comment by jpmeijers** [comment]
Even with that missing my serial loopback works fine. I have a short between PA2 and PA3 and another short between PC1 and PC0.

mbed0s 6.15.0
stm32customtargets master 7b869b6248561742974a66732aca17731d805874
Target: LORA_E5
Build profile: DEBUG and RELEASE tested

mbed_app.json
```json
{
    "config": {
        "main_stack_size":     { "value": 4096 }
    },
    "target_overrides": {
        "*": {
            "platform.stdio-convert-newlines": true,
            "platform.stdio-baud-rate": 115200,
            "platform.default-serial-baud-rate": 115200,
            "mbed-trace.enable": false,
            "mbed-trace.max-level": "TRACE_LEVEL_DEBUG"
        }
    }
}
```

main.cpp
```cpp
#include "mbed.h"

UnbufferedSerial pc(PB_6, PB_7); // UART_1
UnbufferedSerial loop(PA_2, PA_3); // UART_2
// UnbufferedSerial loop(PA_2_ALT0, PA_3_ALT0); // LPUART_1
// UnbufferedSerial loop(PC_1, PC_0); // LPUART_1

int main()
{
    printf("Startup\n");
    char byteRead = 0;
    while (true) {
        while(pc.readable()) {
            pc.read(&byteRead, 1);
            loop.write(&byteRead, 1);
        }
        while(loop.readable()) {
            loop.read(&byteRead, 1);
            pc.write(&byteRead, 1);
        }
    }
}
```

And also testing both UART2 and LPUART at the same time works
```cpp
#include "mbed.h"

UnbufferedSerial pc(PB_6, PB_7); // UART_1
UnbufferedSerial loop(PA_2, PA_3); // UART_2
// UnbufferedSerial loop(PA_2_ALT0, PA_3_ALT0); // LPUART_1
UnbufferedSerial loopLp(PC_1, PC_0); // LPUART_1

int main()
{
    printf("Startup\n");
    char byteRead = 0;
    while (true) {
        while(pc.readable()) {
            pc.read(&byteRead, 1);
            loop.write(&byteRead, 1);
            loopLp.write(&byteRead, 1);
        }
        while(loop.readable()) {
            loop.read(&byteRead, 1);
            pc.write(&byteRead, 1);
        }
        while(loopLp.readable()) {
            loopLp.read(&byteRead, 1);
            pc.write(&byteRead, 1);
        }
    }
}
```

```
[09:16:16:190] Startup␍␊
[09:16:20:980] asfasdfasd␍␊ -- only PA2/PA3 shorted
[09:16:30:445] aassffaassddffaassdd␍␍␊ -- PA2/PA3 and PC1/PC0 shorted
```

Maybe something else in @hallard's code is interfering with UART2? @hallard can you maybe run this simple loopback program and see if that works for you?

**Comment by jeromecoutant** [comment]
> Maybe because UART2 is missing in https://github.com/ARMmbed/mbed-os/blob/master/targets/TARGET_STM/TARGET_STM32WL/serial_device.c#L61-L73

Corrected in https://github.com/ARMmbed/mbed-os/pull/15134

**Pull request merged**
