### PR TITLE
NEW targets: MTB_MURATA_ABZ

### PR DESCRIPTION
**Pull request by jeromecoutant**
This follows discussion started in https://github.com/ARMmbed/mbed-os/issues/14695

This pull request takes configuration files from mbed-os-5.15 branch,
and only check build.

NB: "MBEDTLS_CONFIG_HW_SUPPORT" macro is not enabled, as this needs some development in https://github.com/ARMmbed/mbed-os/tree/master/connectivity/drivers/mbedtls/TARGET_STM
Any help is welcome ! :-)

### CODE REVIEW

**Comment by hallard** [comment]
Awesome thanks, I need to test that on these old test lab boards

image


image

**Comment by jeromecoutant** [comment]
Lora part is missing.
Which component should be added ? SX1276 ?

**Comment by hallard** [comment]
From my point of view it's exactly the same than `TARGET_DISCO_L072CZ_LRWAN1` except that the CPU is L082 instead of L072
Removing of course all arduino pinout compatibility stuff and LED1 .. LED3

**Comment by factoryal** [comment]
Awesome! thanks for opening this issue!
I also developing my custom board with this module and I can't wait for supporting latest mbed! :):)
IMG_3026

**Comment by hallard** [comment]
> From my point of view it's exactly the same than `TARGET_DISCO_L072CZ_LRWAN1` except that the CPU is L082 instead of L072
> Removing of course all arduino pinout compatibility stuff and LED1 .. LED3

ok this is confirmed by [#14695](https://github.com/ARMmbed/mbed-os/issues/14695#issuecomment-882177642)

**Comment by jeromecoutant** [comment]
> 
> 
> Lora part is missing.
> Which component should be added ? SX1276 ?

So I can add this SX1276 component in the custom_target file ?

**Comment by hallard** [comment]
> > Lora part is missing.
> > Which component should be added ? SX1276 ?
> 
> So I can add this SX1276 component in the custom_target file ?

Sure, same as this [one](https://github.com/ARMmbed/mbed-os/blob/master/connectivity/drivers/lora/COMPONENT_SX1276/mbed_lib.json), for the pinout of course

**Comment by factoryal** [comment]
It supports AES-128 and RNG as shown on this webpage below and STM32CubeMX.
https://www.st.com/en/microcontrollers-microprocessors/stm32l082cz.html
image

**Comment by jeromecoutant** [comment]
Oh, you're right...
I can't add LORA component, here, in the custom target json file....
This will not compile as the COMPONENT_SX1276/mbed_lib.json is not updated with the module...

The only thing I can do is to add the information in the readme to add:

````
    "target_overrides": {
        "MTB_MURATA_ABZ": {
            "sx1276-lora-driver.spi-mosi":       "PA_7",
            "sx1276-lora-driver.spi-miso":       "PA_6",
            "sx1276-lora-driver.spi-sclk":       "PB_3",
...
````

**Comment by factoryal** [comment]
@jeromecoutant 
Check here there's defs on this example.
https://github.com/ARMmbed/mbed-os-example-lorawan/blob/development/mbed_app.json#L60-L76

**Comment by hallard** [comment]
> Oh, you're right...
> I can't add LORA component, here, in the custom target json file....
> This will not compile as the COMPONENT_SX1276/mbed_lib.json is not updated with the module...
> 
> The only thing I can do is to add the information in the readme to add:
> 
> ```
>     "target_overrides": {
>         "MTB_MURATA_ABZ": {
>             "sx1276-lora-driver.spi-mosi":       "PA_7",
>             "sx1276-lora-driver.spi-miso":       "PA_6",
>             "sx1276-lora-driver.spi-sclk":       "PB_3",
> ...
> ```

yeah, correct, I dealed with the same since I think we can't  add any `mbed_lb.json` on this repo (sure it's not a lib) the only way and fine is to add it on readme, that's what I've done also on #13

**Comment by evandavey** [comment]
Can we please confirm how to deep sleep for this module (particularly with respect to how TCXO can be GPIO controlled) and what real-world deep sleep current to expect when running MBED.  I've been attempting to use this target for some time (in earlier MBED versions then with a custom target) but have never been able to achieve deep sleep currents for long-term battery operation as a lora node.   I've also typically had to set  "lora.max-sys-rx-error": 100 for it to join reliably.

**Pull request merged**
