### PR TITLE
RAK3172 Allow LPUART1 on PC0/PC1

### PR DESCRIPTION
**Pull request by hallard**

### CODE REVIEW

**Review by jeromecoutant — APPROVED** [review]

**Comment by jeromecoutant** [comment]
Mmm I merged to quickly....
Forgot to check the checks!
https://github.com/ARMmbed/stm32customtargets/actions/runs/6323743976/job/17171919781?pr=37

**Comment by hallard** [comment]
saw that but don't understand why, check errors looks like not related to my changes

**Comment by jeromecoutant** [comment]
PC_0 and PC_1 are missing in TARGET_STM32WL/TARGET_RAK3172/PinNames.h

**Comment by hallard** [comment]
interesting, may be RAK3172 don't expose these pins will fix immediately

**Comment by hallard** [comment]
should be fixed by this one #38

BTW just checked PC0/PC1 are not exposed on RAK3172 non SiP version
https://docs.rakwireless.com/Product-Categories/WisDuo/RAK3172-Module/Datasheet/#hardware

**Pull request merged**
