### PR TITLE
add new boards and documentation

### PR DESCRIPTION
**Pull request by hallard**
replace #13

### CODE REVIEW

**Comment by jeromecoutant** [comment]
If you have pushed this commit into your E5_DevBoard branch, it would be the same....

**Comment by hallard** [comment]
> If you have pushed this commit into your E5_DevBoard branch, it would be the same....

but it would not have been cleaned not?

I created new branch from master (so clean and updated) and put the modified files from E5_DevBoard so you're right the content is the same but clean, thought you wanted clean one. The deal is that I can't do anything to go back with commits already pushed like E5_DevBoard, just can add commit (added automatic to opened PR). To be honest I'm lost in what you want me to do and how to do once commit are pushed and on a PR. Sorry about that.

**Comment by jeromecoutant** [comment]
> but it would not have been cleaned not?

Yes, with "-f" option: git push <your repo> HEAD -f

**Comment by hallard** [comment]
> > but it would not have been cleaned not?
> 
> Yes, with "-f" option: git push HEAD -f

Ok got it, I'm using GUI client, looks. like don't have all the option, that's why

**Review by jeromecoutant — APPROVED** [review]

**Pull request merged**
