### PR TITLE
moved custom LED/Button on macro

### LINKED ISSUE #8: PinNames.h of inherited board not used
When trying to compile for board `LORA_E5_BREAKOUT` the associated file `PinNames.h` located into `TARGET_LORA_E5_BREAKOUT` is not used but it is the file located into `TARGET_LORA_E5` so the following definitions are missing at compile time and fire an error when trying to use LED1 for example.

```cpp
#define LED1     PB_5
#define LED2     PB_10
#define BUTTON1  PA_0
```

I don't know the best way to fix, we could remove inherit from LORA_E5 but in this case we need to duplicate files `LORA_E5_radio_driver.cpp` and `PeripheralPins.c` into target `LORA_E5_BREAKOUT`or I"m just missing a magic config elswhere so the compiler takes  `PinNames.h` from correct target folder?

Just let me know I'll do the PR

### PR DESCRIPTION
**Pull request by hallard**
Fix #8

### CODE REVIEW

**Comment by jeromecoutant** [comment]
See error in ACI build error: some change in TARGET_STM32WL/CMakeLists.txt seems to be needed.

**Comment by hallard** [comment]
> See error in ACI build error: some change in TARGET_STM32WL/CMakeLists.txt seems to be needed.

yeah it's done, it was compiling on my side with IDE, strange.

**Comment by hallard** [comment]
Looks like checks are being done with some target folder present on master but not anymore on PR, that's why it fails.

**Comment by jeromecoutant** [comment]
Seems you  have to keep CMakeLists.txt in each TARGET_XXX_BREAKOUT directories ?

**Comment by jeromecoutant** [comment]
and I would like to have a clean/nice git tree :-)
Could you squash commits ?

[edit] Ooo, it seems I can do it myself! there is a "squash and merge" option!

**Comment by hallard** [comment]
> and I would like to have a clean/nice git tree :-)
> Could you squash commits ?
> 
> [edit] Ooo, it seems I can do it myself! there is a "squash and merge" option!

Excellent because I did not suceeded when PR is created, I think it should be done before creating PR

**Comment by hallard** [comment]
> Seems you have to keep CMakeLists.txt in each TARGET_XXX_BREAKOUT directories ?

may be, but the directories have been deleted in the PR because not used anymore, that is the issue, if you merge the PR build should works fine again.

**Comment by jeromecoutant** [comment]
@patater @0xc0170 
With CLI2, all targets in custom_targets.json need to have a specific TARGET_xxx directory with a CMakeLists.txt ?

**Comment by hallard** [comment]
> @Patater @0xc0170
> With CLI2, all targets in custom_targets.json need to have a specific TARGET_xxx directory with a CMakeLists.txt ?

Would add "even if they are inherited from an existing target directory?"

**Comment by 0xc0170** [comment]
> With CLI2, all targets in custom_targets.json need to have a specific TARGET_xxx directory with a CMakeLists.txt ?

CMake follows what is set in CMakelists. We keep the naming (TARGET_xxx or FEATURE_ or similar cli1 related prefixes) in Mbed OS to maintain backward compatibility with cli1. This repository should still support cli1, using the naming scheme cli1 has.

**Comment by hallard** [comment]
> > With CLI2, all targets in custom_targets.json need to have a specific TARGET_xxx directory with a CMakeLists.txt ?
> 
> CMake follows what is set in CMakelists. We keep the naming (TARGET_xxx or FEATURE_ or similar cli1 related prefixes) in Mbed OS to maintain backward compatibility with cli1. This repository should still support cli1, using the naming scheme cli1 has.

Thanks for pointing that out, should now be fixed, restored the folder

**Pull request merged**
